// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJpKshqy7wKvsygb8ei39yaDTENb2i5k',
    appId: '1:77250249959:web:dce166a2e4d19339644e42',
    messagingSenderId: '77250249959',
    projectId: 'planttree-f17fd',
    authDomain: 'planttree-f17fd.firebaseapp.com',
    storageBucket: 'planttree-f17fd.firebasestorage.app',
    measurementId: 'G-BHVTKM4698',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDSJrQY4dQKTTO5WDtr1-HrBySSmcT8BM',
    appId: '1:77250249959:android:211f61057bc678b1644e42',
    messagingSenderId: '77250249959',
    projectId: 'planttree-f17fd',
    storageBucket: 'planttree-f17fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLIcJJonWumxy3MKCqD3R3YR29xpqHSfw',
    appId: '1:77250249959:ios:3dd8f11eb4d302d8644e42',
    messagingSenderId: '77250249959',
    projectId: 'planttree-f17fd',
    storageBucket: 'planttree-f17fd.firebasestorage.app',
    iosBundleId: 'com.example.plantapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLIcJJonWumxy3MKCqD3R3YR29xpqHSfw',
    appId: '1:77250249959:ios:3dd8f11eb4d302d8644e42',
    messagingSenderId: '77250249959',
    projectId: 'planttree-f17fd',
    storageBucket: 'planttree-f17fd.firebasestorage.app',
    iosBundleId: 'com.example.plantapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjJpKshqy7wKvsygb8ei39yaDTENb2i5k',
    appId: '1:77250249959:web:95ed61d1ed9eb559644e42',
    messagingSenderId: '77250249959',
    projectId: 'planttree-f17fd',
    authDomain: 'planttree-f17fd.firebaseapp.com',
    storageBucket: 'planttree-f17fd.firebasestorage.app',
    measurementId: 'G-WNPJ2MMVDG',
  );
}
